-- 1. Create Polls Table
create table public.polls (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

-- 2. Update Candidates to belong to a Poll
alter table public.candidates add column poll_id bigint references public.polls(id);

-- 3. Insert Initial Dummy Polls
insert into public.polls (title, description)
values 
  ('Presidential Election 2026', 'Vote for the next President'),
  ('Local Council Election', 'Vote for your local representative');

-- 4. Assign existing candidates to Poll 1 (for backward compat/dummy data)
update public.candidates set poll_id = 1 where poll_id is null;

-- 5. Enable RLS
alter table public.polls enable row level security;
create policy "Enable read access for all users" on public.polls for select using (true);
create policy "Enable insert for all users" on public.polls for insert with check (true);
