-- 1. Create Candidates Table
create table public.candidates (
  id bigint generated by default as identity primary key,
  name text not null,
  party text not null,
  image_url text,
  vote_count bigint default 0
);

-- 2. Insert Initial Dummy Candidates
insert into public.candidates (name, party, image_url)
values 
  ('Alice Johnson', 'Future Party', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice'),
  ('Bob Smith', 'Liberty Party', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob'),
  ('Charlie Brown', 'Green Party', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie');

-- 3. Enable Public Read Access
alter table public.candidates enable row level security;
create policy "Enable read access for all users" on public.candidates for select using (true);
create policy "Enable insert for all users" on public.candidates for insert with check (true);
