-- 1. Create the table
create table public.allowed_voters (
  id bigint generated by default as identity primary key,
  id_number text not null unique,
  is_registered boolean default false,
  wallet_address text
);

-- 2. Insert Dummy Data (Valid IDs)
insert into public.allowed_voters (id_number, is_registered)
values 
  ('123456789012', false),
  ('987654321098', false),
  ('112233445566', false);

-- 3. Enable Row Level Security (RLS) - Optional for Backend-only access but good practice
alter table public.allowed_voters enable row level security;

-- 4. Create Policy to allow read/write access (Simplified for development)
create policy "Enable read access for all users" on public.allowed_voters for select using (true);
create policy "Enable update for all users" on public.allowed_voters for update using (true);
create policy "Enable insert for all users" on public.allowed_voters for insert with check (true);
